### PR TITLE
added reset password functionality

### PR DESCRIPTION
**Pull request by bezmozeg**
added the reset password password functionality
created base templates for all the views in the templates/registration folder
added a forgot password button to the login page that redirects you to the reset password link
currently only sends email to local mail server, will have to check how to implement actually sending emails to given addresses

### CODE REVIEW

**Comment by bezmozeg** [comment]
currently sends email for all accounts associated with the email, once the email field is unique, this should be resolved

**Comment by JoseAntRodriguez** [comment]
Humm I just tried it and I got the error "ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it", not sure if it is because of any kind of setting in my computer. Can anyone else try it and see if it works on their machine?

**Comment by bezmozeg** [comment]
did it happen when you clicked on the send link button? That is because you were unable to send the email since it is only setup to work on a local mail server so far, to run a local debugging mail server, open a new console and write this: m smtpd -n -c DebuggingServer localhost:1025

**Comment by JoseAntRodriguez** [comment]
Okay thank you now it worked like a charm. However we might want the user to enter their username and send an email to the email account linked with said username and only if the user doesn't remember its username we ask them for the email address. This is just a suggestion and given that we are running out of time we can leave this out if you want to.

**Review by JoseAntRodriguez — APPROVED** [review]
Test it, works properly as far as I can tell

**Comment by JoseAntRodriguez** [comment]
Almost forgot about this, in the email that is sent it has the address of the webpage (if testing on a local machine said address would be the localhost IP) instead of the name of the application. I know this is done automatically by Django but, again, if we have time, we might want to look into it in the future

**Comment by bezmozeg** [comment]
okay, thanks for suggestions, changing the email is not a problem, you can easily change it and make it custom, I will look into the entering username suggestion, it will be a bit more complicated since I will have to overwrite the whole view so I have to look into their code on github but it shouldn't be too chalenging, currently on a bus ride so not sure if I can make it today but I will look into it latest tomorrow.

**Pull request merged**
